# -*- coding: utf-8 -*-
"""weather.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oiytx1OBJFBu_ZZ0N7BN9t0CNTdLuCel
"""

import requests

from datetime import  datetime

api_key = 'd0a382a03a4eeca09cc9451f79fb6d6b'
location = input("enter the city name:")
  
complete_api_link ="https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data ['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
data_time = datetime.now().strftime("%d %b %Y |  %I:%M;%S %p ")

print("-----------------------------------------------------------------")
print ("weather stats for -{} || {}". format(location.upper(),data_time))
print("-----------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc : ",weather_desc)
print ("Current humidity: ",hmdt,'%')
print ("Current wind speed : ",wind_spd,'kmph')